import styles from '@/components/Pages/Arts/arts.module.scss'
import MainLayout from '@/app/mainLayout'
import Desktop from '@/components/Pages/Arts/Desktop'

import {fetchAxios} from "@/apiConfig.js";
import {Metadata, NextPageContext} from "next";
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function Arts({ params }: { params: { id: number }}) {
    const arts = await fetchAxios.get(`api/arts/`)
    return (
        <MainLayout theme="--dark">
            <>
                <Desktop list={arts}/>
            </>
        </MainLayout>
    )
}